name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u rectecgrills --password-stdin
          docker build . --file Dockerfile --tag docker.pkg.github.com/rectecgrills/action-slack-notify/action-slack-notify:master
          docker push docker.pkg.github.com/rectecgrills/actions-slack-notify/action-slack-notify:master
