name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rectecgrills/action-slack-notify/action-slack-notify
          username: rectecgrills
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
